import Head from "next/head";
import JogoDaVelha from "@/components/JogoDaVelha";

export default function Home() {
  return (
    <>
      <Head>
        <title>Página Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main> <JogoDaVelha /> </main>
    </>
  );
}
